const { remarkCodeHike } = require("@code-hike/mdx")

const withNextra = require("nextra")({
  theme: "nextra-theme-docs",
  themeConfig: "./theme.config.mjs",
  mdxOptions: {
    remarkPlugins: [[remarkCodeHike, { theme: "material-palenight" }]],
  },
})


module.exports = {
  exportPathMap: async function () {
    return {
      '/': { page: '/01_Linha_de_comandos/comando-and' },
      '/': { page: '/01_Linha_de_comandos/comando-apropos' },
      '/': { page: '/01_Linha_de_comandos/comando-echo' },
      '/': { page: '/01_Linha_de_comandos/comando-env' },
      '/': { page: '/01_Linha_de_comandos/comando-export' },
      '/': { page: '/01_Linha_de_comandos/comando-history' },
      '/': { page: '/01_Linha_de_comandos/comando-man' },
      '/': { page: '/01_Linha_de_comandos/comando-pwd' },
      '/': { page: '/01_Linha_de_comandos/comando-set' },
      '/': { page: '/01_Linha_de_comandos/comando-uname' },
      '/': { page: '/01_Linha_de_comandos/comando-unset' },
      '/': { page: '/01_Linha_de_comandos/comando-whatis' },
      '/': { page: '/01_Linha_de_comandos/comando-whereis' },
      '/': { page: '/01_Linha_de_comandos/multi-comandos' },
      '/': { page: '/01_Linha_de_comandos/or-logico' },
      '/': { page: '/01_Linha_de_comandos/variaveis-especiais' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-bzcat' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-cut' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-head' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-less' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-md5sum' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-nl' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-od' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-paste' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-sed' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-sha256sum' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-sha512sum' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-sort' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-split' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-tail' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-tr' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-uniq' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-wc' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-xzcat' },
      '/': { page: '/02_Processar_fluxos_de_texto/comando-zcat' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-bunzip2' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-bzip2' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-cd' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-cp' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-cpio' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-dd' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-file' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-find' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-gunzip' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-gzip' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-ls' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-mkdir' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-mv' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-rm' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-rmdir' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-tar' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-touch' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-unxz' },
      '/': { page: '/03_Gerenciamento_de_arquivos/comando-xz' },
      '/': { page: '/04_Redirecionamento_de_saida/comando-tee' },
      '/': { page: '/04_Redirecionamento_de_saida/comando-xargs' },
      '/': { page: '/05_Gerenciamento_de_processos/comando-kill' },
      '/': { page: '/05_Gerenciamento_de_processos/comando-killall' },
      '/': { page: '/05_Gerenciamento_de_processos/comando-pgrep' },
      '/': { page: '/05_Gerenciamento_de_processos/comando-pidof' },
      '/': { page: '/05_Gerenciamento_de_processos/comando-pkill' },
      '/': { page: '/05_Gerenciamento_de_processos/comando-ps' },
      '/': { page: '/05_Gerenciamento_de_processos/comando-pstree' },
      '/': { page: '/05_Gerenciamento_de_processos/comando-top' },
    };
  },
  ...withNextra(),
};